### ISSUE TITLE
Spawns

### ISSUE THREAD

**Issue by miraco** [cmangos/tbc-db#463]
Creature Spawns in Instances are incorrect. I would like to help respawning this but i would need a sniffing programm to geht correct spawns from current retail server (7.3) or old sniff datas

**Comment by killerwife** [comment]
I do have such data, but I do not trust unknown people with them. As a result I suggest you pick a smaller target for research/fixing. All people who are worthy of having push rights have my data. You can see that as a personal milestone.

**Comment by miraco** [comment]
Okay i understand this.

And there is no current sniffer? I still have active retail account to get the data by my self

**Comment by killerwife** [comment]
No there is not. It was one of the reasons why my team went all out on data gathering pre 7.3.

**Comment by evil-at-wow** [comment]
Note that with the exception of most TBC instances, there's not really a lot to get in 7.3 now. Most Classic instances have been seriously reworked so your 7.3 data would be semi-worthless. Instances like Scarlet Monastery or Scholomance are totally different now, and in many others they have done significant changes.

Some instances are also pretty good here. I personally respawned Dire Maul East for example from old sniffs, so that should be as good as it could get with what the core allowed. I also provided cala with spawn data for parts of BRD, Scholomance, etc. So can you be a bit more specific about what instances or spawns you're mainly talking here?

**Comment by killerwife** [comment]
@evil-at-wow all raids except ZG and Naxx are on retail still. Same goes for wotlk, and also Wotlk Naxx is 90% the same as vanilla Naxx.

**Comment by miraco** [comment]
I am Talking about Tbc Dungeons and raids and the Spawns in there didnt change

**Comment by evil-at-wow** [comment]
@killerwife Almost. Onyxia's Lair was reworked as well. So from the 7 Classic raids, that leaves only 4 remaining ones in more or less original state, and with Ruins of Ahn'Qiraj retuned in Cataclysm, that's more like half of it, depending on what data you want. As you say, for many purposes even the WoTLK versions of Naxx and Onyxia might do, while for others even Molten Core is not good enough any more (they have done several changes compared to Classic or even TBC times). TBC has more luck, as I already mentioned, where only Zul'Aman got the same treatment as Zul'Gurub. But that's about it, ignoring a few mostly unimportant changes. And I'm ignoring WoLTK entirely because this was logged in TBC-DB :wink:

Anyway, I know there's still plenty of valuable data available now, but the initial issue text was talking about "instances", not raids, and it didn't mention any expansion either. So as far as I knew, the problem could have been "Scholomance, Scarlet Monastery, Wailing Caverns and Sunken Temple". Good luck finding relevant data on retail then, which was what I was pointing out (it would be a waste of time sniffing dungeons on retail that have been completely changed anyway).
But fortunately it's about TBC dungeons and raids, so that's good as there is data available!

**Comment by killerwife** [comment]
@evil-at-wow for everything else, there is @devmaximus :D

**Comment by AnonXS** [comment]
With the maybe soonish to be exported dungeon templates, working on dungeons will get alot easier, reviewable than it is at the moment, making working together on a dungeon a viable option in comparisson to the otherwise complete "refactor" / "rewrites" that are done occasionally.

Closing here as no further information / discussion is given in this thread.
