### ISSUE TITLE
NPC Rokmar the Crackler (SP-HC)

### ISSUE THREAD

**Issue by Jaxson123** [cmangos/tbc-db#721]
https://wowwiki.fandom.com/wiki/Rokmar_the_Crackler

Grievous Wound: Bleed debuff, it causes Rokmar's current target to bleed for 900 physical damage every 2 seconds until the player with the debuff has been healed to full health; Divine Shield and Stoneform will also remove it. Also, the debuff is not timed, and will last until you are dead or cured.

he was using this debuff on random other targets in addition to the tank, probably not intended behaviour.

**Comment by MantisLord** [comment]
```
('1799101','17991','0','0','100','3','8400','15700','20700','35100','0','0','11','31956','1','32','0','0','0','0','0','0','0','0','Rokmar the Crackler (Normal) - Cast Grievous Wound'),
('1799102','17991','0','0','100','5','8400','15700','20700','35100','0','0','11','38801','1','32','0','0','0','0','0','0','0','0','Rokmar the Crackler (Heroic) - Cast Grievous Wound'),
```
TARGET_T_HOSTILE...? Cannot reproduce...

**Comment by Jaxson123** [comment]
https://imgur.com/a/1UA3Dc5

was able to just reproduce the debuff on both targets, was not pulling thread on windfurybot from jaxson he just applied grievous wounds on the shaman after the rogue had it already aswell

**Comment by killerwife** [comment]
This might be an utterly weird question, but were you by any chance testing this on our test server and not locally?

**Comment by Jaxson123** [comment]
it was on the ptr yea

**Comment by AnonXS** [comment]
`Rokmar the Crackler will now only apply Grievous Wound to his current target.`

https://wow.gamepedia.com/Patch_2.1.0

---

All Bug related to Light's Vengeance Servers should be posted here: https://gitlab.com/lights-vengeance/issues/issues, as the Server is **not** 100% identical with cmangos-tbc due to the fact that we try to emulate certain patch stages of the burning crusade expansion.
