### ISSUE TITLE
[Quest] Swift Discipline 

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/tbc-db#787]
https://www.wowhead.com/quest=9066/swift-discipline
In this video that is 8 years old I see different spell cast on this guys and makes them big grey boars not small black boars
https://www.youtube.com/watch?v=w9-XgzbxyFU

**Comment by Arcalypse** [comment]
I was able to find an __even older video_ that confirms that the boars were originally large grey boars.

### Video
[https://youtu.be/LwduWo0C0RE](https://youtu.be/LwduWo0C0RE?t=45) (@ 0:45) - Sep 6, 2008
As you can see in the video, the NPC is turned into a large grey boar.

### [NPC] Apprentice Ralen (_15941_)
***MAP:** 530 (_Outland_)
***ZONE:** 3430 (_Eversong Woods_)
**X:** 9188.75
**Y:** -6712.91
**Z:** 25.9970
**O:** 3.87460

**Teleport to Apprentice Ralen**
`.go 9188.75 -6712.91 25.9970 530`

### [ITEM] Antheol's Disciplinary Rod (_22473_)
**Add Item to Inventory**
`.additem 22473`


### Partial Fix
So the [Boar](https://www.wowhead.com/npc=2809/boar) model is in the database as **607** when it should be **389**. Applying the script below fixes the boar to be the appropriate model.

[https://pastebin.com/kiWv5ENu](https://pastebin.com/kiWv5ENu)

### Still Needs Fixing...
So the main problem is that when Apprentice Ralen morphs, his scale needs to be set to **2** instead of **1**. I believe this must be done via a script, but I am unfamiliar with what needs to take place in order to make that happen. But if someone can get that part sorted, I think this one can be closed.

**Comment by AnonXS** [comment]
Spell does:
```
Id: 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints: 0
Targets: (25, 0) (TARGET_UNIT, TARGET_NONE)
Aura: 56 (SPELL_AURA_TRANSFORM), value: 0, miscA: 2809 (2809), miscB: 0, periodic: 0
```

transforming into

![grafik](https://user-images.githubusercontent.com/19734826/163725513-cefba2bb-0192-4c33-bbbc-e1ca6aeecf2d.png)

![grafik](https://user-images.githubusercontent.com/19734826/163725552-e58cf5c1-0d63-402e-9d75-61dfbcb05c68.png)

```
[0] UpdateType: Values
[0] Object Guid: Full: 0x203AF042400F9240003FDF00003DAF2F Creature/0 R3772/S16351 Map: 530 Entry: 15945 Low: 4042543
[0] UNIT_FIELD_BOUNDINGRADIUS: 1.7639999
[0] UNIT_FIELD_DISPLAYID: 1167

[0] UpdateType: Values
[0] Object Guid: Full: 0x203AF042400F9140003FDF00003DAF2F Creature/0 R3772/S16351 Map: 530 Entry: 15941 Low: 4042543
[0] UNIT_FIELD_BOUNDINGRADIUS: 1.7639999
[0] UNIT_FIELD_COMBATREACH: 1.5
[0] UNIT_FIELD_DISPLAYID: 1167
```
