### ISSUE TITLE
How do I look at Databases and make changes? I'm really new to all this

### ISSUE THREAD

**Issue by Scuba-dooby-doo** [cmangos/tbc-db#788]
I'm a network engineer, so I'm good on routing/switch and IP addressing and such, but I have very little programming knowledge (C++ long ago, and a little Python in college) and no experience navigating databases and working with SQL.  

I'm good at following instructions, so I got a Server 2016 VM machine all setup with Mangos and everything seems to be working as long as I'm running the game from the local server. But when trying to run it from my desktop I get logged in successfully, but can't connect to the "Realm Server". I just try to choose the realm "Mangos" and it loops me back to the realm selection screen again. 

This could very well be just a firewall setting or something that needs to be modified, but before I can really investigate this and do any troubleshooting I need to know how to actually LOOK at and INTERPRET the databases and know how to modify their settings (I'm really looking forward to tweaking the XP rate and see how crazy I can get :D ) 

I've looked at the "Database Structure" guides under "Getting Started" on the CMaNGOS website, but they don't really help me understand HOW to actually go see all those tables. 

I would appreciate any help someone can give on either of my issues. I installed all the software that the Windows setup guide recommended, so I'm good to use any of those tools. 

Thank you very much

**Comment by al3xc1985** [comment]
for modifing settings use mangosd.conf 
you find there xp, rates, and many many other things

**Comment by al3xc1985** [comment]
also in VM you need to check hosts file in windows, I believe you have windows for easier config... you need to add your ip there 2...
also you need your ip into sql database in realmd ... you will find realmlist...add there your ip 2

**Comment by al3xc1985** [comment]
for ports you need to open 8085 wowserver 3724 wowserver 3306 mysql

**Comment by al3xc1985** [comment]
in mangosd.conf you are doing the most basic changes in server... the rest is done through sql knowledge

**Comment by SilvioDoMine** [comment]
Hi @Scuba-dooby-doo, first of all, welcome to our project!

Let me anwser your question first: if you followed the instructions correctly, you now have a **database server**, which stores all information regarding your realms, characters and world. And what I understood of your question is "How do I connect and see all this data?". And the awnser for that is simple: you need a Database Client to connect to your server.

You can use several clients, such as Mysql Workbench (Free and a little complex, but robust), Heidi (Free, simple), Navicat (Paid, easy to use, simple), etc. I recommend you Heidi SQL for starters, download it and look for tutorials in how to connect into your server.

----------------

Now, regarding your error. This may be caused because you have do configure your realmlist (access your database, and check into REALMIST)

**Comment by Scuba-dooby-doo** [comment]
Thank you everyone for your helpful comments. I learned a lot since making this post, and it did end up being the IP in the Realmlist table that I had to adjust. 

Thank you very much
