### ISSUE TITLE
Quest 1920 - Investigate the Blue Recluse - missing afterscript

### ISSUE THREAD

**Issue by killerwife** [cmangos/tbc-db#826]

**Comment by Grz3s** [comment]
Quest has `start script`  - no `afterscript` ... fix added

**Comment by MilkmanMHOC** [comment]
Just thought i would add on classic, how this error is behaving as i am not sure the above fix is the same problem the classic is having. 

It appears the apothecarium is overan with rift spawns  as soon as anyone enters the area after a fresh restart of the server (or anytime there after).  No mages on the server were high enough yet to start the quest to make them appear.  The lowbie undead are getting massacred as they walk though.  Its kind of funny, but likely not intended. 

This info may or maynot be redundant to the issue as understood by those fixing it, but thought it couldn't hurt to add more info.

**Comment by MilkmanMHOC** [comment]
Thanks for the quick response.  I just updated the server last weekend to the newest everything and the issue still occurs which is why i went searching again and put the above into up just in case.

**Comment by Grz3s** [comment]
fix is added to WoTLKDB ... and labeled `Awaiting backport` - to TDB and CDB... 
so i would check that first...
BTW:
Backporting between DBs sometiomes is not `ctrl+c`&`ctrl+v`.. some guids may be dif etc...
i'll leave it for CDB devs to check

**Comment by cala** [comment]
All related backports were already made to Classic DB. The aggro issue comes from the fact that Spawn Rifts have a faction that is hostile to players, making them aggro on sight.

This is not an issue in TBC and WotLK cores where invisibility is handled like a phase : units having an invisibility type can only see and be seen by units having the same invisibility type. This mechanics was introduced in TBC, as a generic rule for the mage invisibility.

But in Classic, invisibility was handled more like AD&D invisibility : invisible units could see visible units. This is what made the infamous invisible ghosts in Dire Maul West or the invisible specters in Eastern Plaguelands so deadly because they were noticed only when they started attacking... unexpected.

Thus, I have to handle the peticular case of Rift Spawn that should not aggro hostile players when they see them. I will do this soon.

**Comment by killerwife** [comment]
The invisibility thing is something that was always in WOTLK but I changed it in TBC 2 years ago after confirming in Skettis in TBC that it works like this. Just need to find my commit and push it to vanilla I guess.

**Comment by cala** [comment]
@killerwife One or two years ago, you indeed made many changes to visibility, I remember that.
But this led to incorrect behaviours in Classic core that I adjusted later to be correct. So, fortunately, no need to change anything in Classic core. 😄 

Only this NPC that is like an edge case needs to be adjusted and I will do it soon.

**Comment by cala** [comment]
The aggro issue is fixed by https://github.com/cmangos/classic-db/commit/89357fd36b174808e7ca372a13939802b91647e5 (Classic only).

**Comment by killerwife** [comment]
I wonder what the incorrect behaviours were, since that is kinda important.

**Comment by Grz3s** [comment]
what i found with this.. it that Cala made his own script for this quest... i found it while doing backports... so i just skipped...(didnt checked how diff it was ..but that could be issue in first place)
