### ISSUE TITLE
NPC 17160 - Living Cyclone - Nagrand

### ISSUE THREAD

**Issue by SabriynaVermillion** [cmangos/tbc-db#968]
- double spawn for creature living cyclone in nagrand

look at GUID 151754 and GUID 151755

**Comment by MantisLord** [comment]
Normally these would be duplicates but this is actually a really weird case where it's intentional. There are actually two possible spawns per location on retail apparently.

https://github.com/cmangos/tbc-db/commit/b011d47df363fd65f1128b7dd0c0831ed01fa4d8#diff-173d8d22c8fcb65931f93dffef6c2659e227eaa49a713857f6ce25c909399a6aR447

Don't know if this is a perfect implementation, but these mobs need to be studied carefully and tweaked if there's something different from retail behavior rather than cleaned up/deleted.
